* Synopsis
A simple Emacs interface for Reek.
* Installation
Please, note that the current version of reek.el requires [[https://github.com/troessner/reek][Reek]]
* Manual
Just drop reek.el and dash.el. somewhere in your load-path. I favour the folder ~/.emacs.d/vendor:
#+begin_src elisp
  (add-to-list 'load-path "~/.emacs.d/vendor")
  (require 'reek)
#+end_src
* Usage
| Command                     | Description                                   | Reek mode binding |
|-----------------------------+-----------------------------------------------+-------------------|
| M-x reek-check-project      | Runs Reek on the entire project               | C-c C-e p         |
| M-x reek-check-directory    | Prompts from a directory on which to run Reek | C-c C-e d         |
| M-x reek-check-current-file | Runs Reek on the currently visited file       | C-c C-e f         |

If you use them often you might want to enable reek-mode which will added some keybindings for them:
#+begin_src elisp
  (add-hook 'ruby-mode-hook #'reek-mode)
#+end_src
* Credit
Majority part of code is from [[https://github.com/bbatsov/rubocop-emacs][RuboCop Emacs]]
* Bugs & Improvements
Bug reports and suggestions for improvements are always welcome. GitHub pull requests are even better! :-)

Cheers,
Daniel
